### PR TITLE
Re-organize some of the code

### PR DESCRIPTION
**Pull request by astrofrog**
@keflavich - this is work I did today to try and tidy up the code a bit - I didn't split out the Qt viewer from the Glue viewer yet (will explain later) but I added an example that shows how to run it standalone (without launching the main Glue GUI).

What branch of pyspeckit do I need to test this? (the stable version doesn't seem to work as there are missing functions/methods)

### CODE REVIEW

**Comment by astrofrog** [comment]
You can also run the control panel standalone by just doing:

```
python pyspeckit_viewer/control_panel.py 
```

**Comment by astrofrog** [comment]
@keflavich - this now appears to work at least at the same level as before, so I'm going to go ahead and merge.

While working on a standalone viewer, I realized that we're quite dependent on glue for things like the horizontal range selection, so it's hard to separate out a pure GUI that doesn't depend on glue. However, as shown in the example.py file this doesn't mean you have to launch glue. So maybe it just makes sense to leave it as one viewer, and you could just say (if we merge this into pyspeckit) that this viewer requires glue? But you can still provide a way to launch it as done in example.py?

**Comment by keflavich** [comment]
@astrofrog OK, that's fine by me.  I don't think we're entirely dependent on glue for horizontal range selection, since that can still be done through the normal "splot-like" interface from within glue.

**Comment by astrofrog** [comment]
@keflavich - right, there are other bits like for example we re-use the convenience classes in glue that help put a matplotlib canvas in Qt, etc. But I'll think again about whether we can better separate things.

**Pull request merged**
